name: Sonar Scan

on: [push, pull_request]

jobs:
  regression_tests:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - uses: mathrix-education/sonar-scanner@master
        with:
          version: 4.2.0.1873 # required
          typescript: true
          scan: true
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Setup SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

      - name: Run Scanner
        run: |
          docker run --rm -i -v $GITHUB_WORKSPACE/src --link sonarqube newtmitch/sonar-scanner sonar-scanner