name: Regression Suite

on: [push, pull_request]

jobs:
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Setup SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

      - name: Run Scanner
        run: |
          docker run --rm -i -v $GITHUB_WORKSPACE/src --link sonarqube newtmitch/sonar-scanner sonar-scanner -Dsonar.host.url=http://127.0.0.1:9092